refactor: users module rename to professionals
VAIRIX/cvs-backend pull request #4
Opened 2022-12-12 20:31 UTC by munozlucas

[Trello ticket](https://trello.com/c/VMGSqcne/35-change-user-module-to-professional)

- Rename users module to professionals

2022-12-12 20:45 UTC, marianozunino approved these changes

2022-12-12 22:50 UTC, marianozunino approved these changes
:shipit:

2022-12-12 23:44 UTC, munozlucas commented
> :shipit:

I need another aprove to merge :sweat_smile:

2022-12-13 02:29 UTC, marianozunino approved these changes

2022-12-13 14:01 UTC, marianozunino approved these changes

2022-12-13 14:03 UTC, marianozunino requested changes
test

2022-12-13 14:12 UTC, merged